#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/markdown_go
  
  rm -rf tmp/* 
  
  pySloc -L go cmd/xgoMarkdown/xgoMarkdown.go cmd/commonTests/commonTests.go  -X *.pb.go -X commonmark -X markdown-testsuite -v $@
else
  echo "DEV_BASE is not defined"
fi
